### ISSUE TITLE
[Bug] DBT Deprecated functionality - `freshness` as a top-level property

### ISSUE THREAD

**Issue by felipecoxanet** [fivetran/dbt_fivetran_log#151]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the issue

Error in DBT Cloud Jobs:

```
03:00:29  [WARNING]: Deprecated functionality
Found `freshness` as a top-level property of `fivetran_platform` in file
`models/staging/src_fivetran_platform.yml`. The `freshness` top-level property
should be moved into the `config` of `fivetran_platform`.
```

Is needed change the file to adjust the freshness configuration:
From:
```
    freshness:
      warn_after: {count: 72, period: hour}
      error_after: {count: 96, period: hour}
```

To:
```
    config:
        freshness:
          warn_after: {count: 72, period: hour}
          error_after: {count: 96, period: hour}
```

### Relevant error log or model output

```shell
03:00:29  [WARNING]: Deprecated functionality
Found `freshness` as a top-level property of `fivetran_platform` in file
`models/staging/src_fivetran_platform.yml`. The `freshness` top-level property
should be moved into the `config` of `fivetran_platform`.
```

### Expected behavior

no deprecation error message

### Possible solution

Is needed to change the file to adjust the freshness configuration:
From:
```
    freshness:
      warn_after: {count: 72, period: hour}
      error_after: {count: 96, period: hour}
```

To:
```
    config:
        freshness:
          warn_after: {count: 72, period: hour}
          error_after: {count: 96, period: hour}
```

### dbt Project configurations

Is needed to change the file to adjust the freshness configuration:
From:
```
    freshness:
      warn_after: {count: 72, period: hour}
      error_after: {count: 96, period: hour}
```

To:
```
    config:
        freshness:
          warn_after: {count: 72, period: hour}
          error_after: {count: 96, period: hour}
```

### Package versions

```
  - package: fivetran/fivetran_log
    version: 2.1.0
```

### What database are you using dbt with?

snowflake

### How are you running this dbt package?

dbt Cloud™

### dbt Version

![Image](https://github.com/user-attachments/assets/1c017c72-67da-4feb-a164-245d71d3e277)

### Are you willing to open a PR to help address this issue?

- [x] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.
