### ISSUE TITLE
BUG - fivetran_utils 0.3.2 has incompatible dependency on fivetran_utils vs hubspot

### ISSUE THREAD

**Issue by joellabes** [fivetran/dbt_fivetran_log#19]
**Are you a current Fivetran customer?** 
Please tell us your name, title and company
Yes! Joel, Head of Data & Insights at Education Perfect

**Describe the bug**
We did a revamp of our packages after upgrading to dbt 0.20.0, but the triangle of fivetran_log, hubspot, and dbt_expectations has gotten us into trouble. 

**Steps to reproduce**
Our desired packages.yml: 

```yml
packages:

  - package: dbt-labs/audit_helper
    version: 0.4.0

  - package: dbt-labs/codegen
    version: 0.4.0

  - package: dbt-labs/redshift
    version: 0.5.0

  - package: fivetran/fivetran_log
    version: [">=0.3.0", "<0.4.0"]

  - package: fivetran/hubspot
    version: [">=0.4.0", "<0.5.0"]

  - package: calogica/dbt_expectations
    version: 0.4.0
```
Output of `dbt deps`:

```

PS C:\WF\LP\data-insights\ep-dbt> dbt deps
Running with dbt=0.20.0
Encountered an error:
Version error for package fivetran/fivetran_utils: Could not find a satisfactory version from options: ['>=0.1.0', '<0.2.0', '>=0.2.0', '<0.3.0']
```

**Expected behavior**
Successful installation of all dependencies 

**Warehouse** 
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
Output when fivetran_log is commented out: 
```
PS C:\WF\LP\data-insights\ep-dbt> dbt deps
Running with dbt=0.20.0
Installing dbt-labs/audit_helper@0.4.0
  Installed from version 0.4.0
Installing dbt-labs/codegen@0.4.0
  Installed from version 0.4.0
Installing dbt-labs/redshift@0.5.0
  Installed from version 0.5.0
Installing fivetran/hubspot@0.4.0
  Installed from version 0.4.0
Installing calogica/dbt_expectations@0.4.0
  Installed from version 0.4.0
Installing dbt-labs/dbt_utils@0.7.0
  Installed from version 0.7.0
Installing fivetran/hubspot_source@0.4.0
  Installed from version 0.4.0
Installing calogica/dbt_date@0.4.0
  Installed from version 0.4.0
Installing fivetran/fivetran_utils@0.2.1
  Installed from version 0.2.1
```

Output when fivetran/hubspot's version is `">=0.3.0", "<0.4.0"` (I assume it references fishtown-analytics/dbt-utils but haven't checked): 
```
PS C:\WF\LP\data-insights\ep-dbt> dbt deps
Running with dbt=0.20.0
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```

**Screenshots**

**Please indicate the level of urgency** 

I can work around this by disabling fivetran_log, but that's a pain

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
