### ISSUE TITLE
BUG - unable to install dbt v0.20.0 because of dbt utils fishtown v0.6.6 dependency

### ISSUE THREAD

**Issue by edbizarro** [fivetran/dbt_fivetran_log#21]
**Are you a current Fivetran customer?** 

Yes

**Describe the bug**

this package has a dependency on dbt utils v0.6.x, but to be able to install on dbt v.20 (along with another packages like dbt-expectations) the utils package has to be .7.x

**Expected behavior**

**Project variables configuration**

```yml
copy dbt_project.yml here
```

**Package Version**

```yml
packages:
  - package: calogica/dbt_expectations
    version: [">=0.4.0"]
  - package: fivetran/fivetran_log
    version: [">=0.3.2"]
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

```
Running with dbt=0.20.0
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```

**Screenshots**

**Please indicate the level of urgency** 

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
