### ISSUE TITLE
BUG - [your bug title here]

### ISSUE THREAD

**Issue by ipear3** [fivetran/dbt_fivetran_log#23]
**Are you a current Fivetran customer?** 
Yes. My name is Ian Pearthree. I am a data engineer at Pendo.

**Describe the bug**
Our fivetran_log__connector status page says a connector is broken, but it is actually successfully syncing historical data.

**Steps to reproduce**
Configure a Pendo connector, then enable the connector. This will correctly start a priority-first sync. You'll also need to configure and enable a fivetran_log connector.
Then, install the fivetran_log dbt package to your DBT instance. Run the models contained in the package.
Then, check out the table built by the fivetran_log__connector_status model. The Pendo connector has a connector_health of "broken".
Then, check out the connector in you fivetran dashboard. The connector will have a green active status, and will indicate that the priority data sync is complete, and the historical sync may continue to run. All the UI elements indicate that the connector is healthy, and operating as intended.

**Expected behavior**
I would expect the Pendo connector in the fivetran_log__connector_status to have a "connected" connector_health value. If not "connected", then I'd expect a status like "priority first sync", so that it accurately reflects the status indicated by the fivetran UI.

**Project variables configuration**
```yml
name: 'analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Model Configuration
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
    +persist_docs: # Create BigQuery descriptions for objects with resource descriptions.
        relation: True
        columns: True
    analytics:
     # Applies to all Files under models/temp
        materialized: table
        intermediate:
            dataset: staging
        final:
            dataset: final
        staging:
            schema: staging
        views:
            schema: views
        temp:
            schema: temp
    jira_source:
        +schema: staging
    jira:
        +schema: fivetran_jira
        intermediate:
            +schema: staging
    zendesk_source:
        +schema: staging
    zendesk:
        +schema: pendo_zendesk
        agent_work_time:
            +schema: staging
        intermediate:
            +schema: staging
        reply_times:
            +schema: staging
        sla_policy:
            +schema: staging
        ticket_history:
            +schema: staging
        utils:
            +schema: staging
    salesforce_source:
        +schema: staging
    salesforce:
        +schema: fivetran_salesforce
        intermediate:
            +schema: staging

vars:
    jira_schema: fivetran_jira
    jira:
        issue_field_history_columns: [
            "timespent",
            "assignee",
            "lastViewed",
            "summary",
            "resolutiondate",
            "creator",
            "resolution",
            "updated",
            "description",
            "timeoriginalestimate",
            "issuekey",
            "timeestimate",
            "security",
            "parent",
            "priority",
            "created",
            "workratio",
            "statuscategorychangedate",
            "statuscategory",
            "environment",
            "project",
            "issuetype",
            "reporter",
            "components",
            "labels",
            "versions",
            "fixVersions",
            "customfield_12602",  # The custom field for zendesk ticket count
            "customfield_12735", # one of the 'severity' fields
            "customfield_12100", #another 'severity' field
            "customfield_10114", # 'Team'
            "customfield_12801", # 'Team name'
            "customfield_11201", # 'Dev team'
            "customfield_12720", # 'Team'
            "customfield_12760", # 'Value proposition'
            "customfield_12508", # 'Buisness value'
            "customfield_12836" # 'Dev SOC Trust values'
        ]
    zendesk_schema: pendo_zendesk
    salesforce_schema: fivetran_salesforce
    fivetran_log:
        fivetran_log_using_transformations: false # this will disable all transformation + trigger_table logic
        fivetran_log_using_triggers: false # this will disable only trigger_table logic

```

**Package Version**
```yml
packages:
  - package: fivetran/jira_source
    version: 0.2.0
  - package: fivetran/jira
    version: 0.3.0
  - package: fivetran/zendesk_source
    version: 0.3.0
  - package: fivetran/zendesk
    version: 0.4.0
  - package: fivetran/salesforce_source
    version: 0.2.1
  - package: fivetran/salesforce
    version: 0.3.1
  - package: fivetran/fivetran_log
    version: 0.3.0
```

**Warehouse**
BigQuery

**Additional context**
I think the source of the issue is no end date in the fivetran_log.log table for the connector in question (connector_id = reclusive_reprimand)

**Screenshots**
![image](https://user-images.githubusercontent.com/52967928/134713298-d2d8774a-11ca-4361-8970-dd4465ff512a.png)
![image](https://user-images.githubusercontent.com/52967928/134713363-5bcbe685-9b95-4f06-afc9-21139daeb787.png)
![image](https://user-images.githubusercontent.com/52967928/134713390-34e37fa7-91f2-4e0c-a9ee-99316aa60be4.png)
![image](https://user-images.githubusercontent.com/52967928/134714039-a48ffcc1-74d6-4b47-9b21-e36b8c0b535e.png)

**Please indicate the level of urgency** 
Surfacing connector statuses is a quarterly objective for us, with a deadline of October 31st.

**Are you interested in contributing to this package?** 
No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
