### ISSUE TITLE
BUG - Issue upgrading this package to 0.4.1 while also using dbt 0.21.0

### ISSUE THREAD

**Issue by jcbmllgn** [fivetran/dbt_fivetran_log#26]
**Are you a current Fivetran customer?** 
Yes, Firefly Health

**Describe the bug**
I'm running into an error when upgrading to `fivetran_log` version `0.4.1` when also using dbt version `0.21.0`. Here's the error I'm running into: 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/1261230/140306757-b7adb97a-0bcf-4cdd-8852-f995455758b1.png">

Here's the command I ran `dbt run -m fivetran_log__connector_status`. I do not have this issue when using Fivetran_log@0.4.0 and dbt@0.20.0, I also do not have this issue when using Fivetran_log@0.4.0 and dbt@0.21.0

The upper part of the image is just showing the `package.json` file, as of execution all packages were running with the latest version. 

**Project variables configuration**

```yml
name: "firefly"
version: "1.0.0"
config-version: 2

profile: "default"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "logs"

on-run-start: 
    - "{{ create_share('zeus_ff_claims', ['XPA62986']) }}"
      #for more info: https://discourse.getdbt.com/t/using-dbt-snowflake-shares/1110

    - "{{ grant_permissions_on_schema()}}"
    - "{{ create_snowflake_users_and_grant_roles()}}"


on-run-end:
  - "{{ share_table('PUBLIC', 'patient_roster_reconciliation', 'zeus_ff_claims') }}"
  - "{{ share_table('PUBLIC', 'all_claims', 'zeus_ff_claims') }}"
  - "{{ grant_select_on_schemas(schemas, 'looker_role') }}"
  - "{{ grant_select_on_schemas(schemas, 'analyst') }}"

seeds:
  +quote_columns: false

vars:
  fivetran_log:
    # Link to the package that relies on these vars:
    # https://hub.getdbt.com/fivetran/fivetran_log/latest/
    fivetran_log_database: raw
    fivetran_log_schema: fivetran_logs

  # Link to the package that relies on these vars:
  # https://hub.getdbt.com/fivetran/linkedin/latest/
  linkedin_database: raw
  linkedin_schema: linkedin_ads

  segment:
    # The module assumes that it is drawing from the 'PAGES' table that is generated by Segment
    # However, our use case requires extensions, handled in this DAG node
    # https://hub.getdbt.com/fishtown-analytics/segment/latest/
    segment_page_views_table: "{{ ref('webflow_pages_extended') }}"

  # https://github.com/fivetran/dbt_salesforce_source
  salesforce_source:
    salesforce_database: raw
    salesforce_schema: salesforce

    using_account_history_mode_active_records: true
    using_opportunity_history_mode_active_records: true
    using_user_role_history_mode_active_records: true
    using_user_history_mode_active_records: true

    opportunity_pass_through_columns: [
      OPPORTUNITY_TYPE_C, 
      SDR_REP_C, 
      SDR_MEETING_SCHEDULED_DATE_C,
      EXPECTED_LIVES_C,
      SDR_MEETING_OUTCOME_C
    ]

    account_pass_through_columns: [
      LEAD_TYPE_C,
      COMPANY_TYPE_C,
      NUMBER_OF_LOCATIONS_C,
      INSURANCE_CARRIER_C
    ]

  salesforce:
    opportunity_enhanced_pass_through_columns: [
      ACCOUNT.LEAD_TYPE_C,
      ACCOUNT.COMPANY_TYPE_C,
      ACCOUNT.NUMBER_OF_LOCATIONS_C,
      ACCOUNT.INSURANCE_CARRIER_C
    ]

  # https://github.com/fivetran/dbt_salesforce
  salesforce_database: raw
  salesforce_schema: salesforce

  jira_database: raw
  jira_schema: jira_fivetran
  jira:
    # Field options can be found with this query:
    # select name from RAW.JIRA_FIVETRAN.FIELD;
    issue_field_history_columns: ['Labels', 'Key', 'Epic Name', 'Severity', 'Project']

  github_source:
    github_database: raw
    github_schema: github_fivetran

  'dbt_date:time_zone': 'America/New_York'
  dbt_artifacts:
    dbt_artifacts_database: analytics
    dbt_artifacts_schema: dbt_artifacts
    dbt_artifacts_table: artifacts
```

**Package Version**

```yml
packages:
# OC - Packages last updated 09/17/2021
  - package: dbt-labs/dbt_utils
    version: 0.7.3

  - package: dbt-labs/segment
    version: 0.6.0

  - package: fivetran/fivetran_log
    version: 0.4.1

  - package: fivetran/salesforce_source
    version: 0.3.1

  - package: fivetran/salesforce
    version: 0.4.0

  - package: fivetran/jira
    version: 0.5.1

  - package: calogica/dbt_date
    version: 0.4.1

  - package: tailsdotcom/dbt_artifacts
    version: 0.5.0

  - package: fivetran/github
    version: 0.3.0

  - package: fivetran/github_source
    version: 0.3.0
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Low urgency. We're able to upgrade to dbt@0.21.0 without this minor point version upgrade. 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
