### ISSUE TITLE
BUG - The stg_fivetran_log__log model does now handle duplicate rows in the source logs table

### ISSUE THREAD

**Issue by jcbmllgn** [fivetran/dbt_fivetran_log#34]
**Are you a current Fivetran customer?** 
Jacob Mulligan, head of analytics, Firefly Health

**Describe the bug**
We are currently experiencing an issue where the `stg_fivetran_log__log` and `fivetran_log` models are failing from the following issues:

```
09:40:01  Failure in test dbt_utils_unique_combination_of_columns_fivetran_log__schema_changelog_connector_id__destination_id__created_at (models/fivetran_log.yml)
09:40:01    Got 7 results, configured to fail if != 0
09:40:01  
09:40:01    compiled SQL at target/compiled/fivetran_log/models/fivetran_log.yml/dbt_utils_unique_combination_o_a484aa854783c3b3614d0db8c28551e9.sql
09:40:01  
09:40:01  Failure in test dbt_utils_unique_combination_of_columns_stg_fivetran_log__log_log_id__created_at (models/staging/stg_fivetran_log.yml)
09:40:01    Got 1423 results, configured to fail if != 0
09:40:01  
09:40:01    compiled SQL at target/compiled/fivetran_log/models/staging/stg_fivetran_log.yml/dbt_utils_unique_combination_o_124db0b56a6fac04fff9f44f342dcecf.sql
```

The root issue is that there actually is row duplication in the `logs` table created by the [Fivetran Logs](https://fivetran.com/docs/logs/fivetran-log) connector. 

I first ran the SQL for the above `dbt_utils_unique_combination_of_columns_stg_fivetran_log__log_log_id__created_at` test failure which led me to a few specific duplicate rows:

```sql
    select
        log_id, 
        created_at,
        count(*)
    from analytics.dbt_jacob_mulligan_stg_fivetran_log.stg_fivetran_log__log
    group by log_id, created_at
    having count(*) > 1
;
```

I then ran this SQL to confirm that there are duplicate rows across the `log_id` and `created_at` columns in the raw log data that Fivetran has written into Snowflake:

```sql
    select *
    from raw.fivetran_logs.log
    where 
        id = 'logic_exporting'
        and time_stamp = '2022-02-09 18:52:45.842 +0000'
```

When I run this SQL I get the following output (sorry for the terrible output, I don't know how to format this better!) Notice that the only difference is in the `SEQUENCE_NUMBER` column, `16,112` vs `16,117`. 
```csv
TIME_STAMP	CONNECTOR_ID	TRANSFORMATION_ID	EVENT	MESSAGE_EVENT	MESSAGE_DATA	_FIVETRAN_SYNCED	ID	SYNC_ID	SEQUENCE_NUMBER	PROCESS_ID
2022-02-09 18:52:45.842 +0000	logic_exporting		INFO	copy_rows	{"schema":"fivetran_wick_crumpet_staging","name":"lucian_public_tasks-staging-4f8f229f-5b71-465a-8c71-fe4a47e25695"}	2022-02-09 19:16:13.412 +0000	logic_exporting	b5e47b18-dc88-4246-9f33-64512205e195	16,112	4e4d37a2-b9b9-43be-b9ea-45715f302903
2022-02-09 18:52:45.842 +0000	logic_exporting		INFO	copy_rows	{"schema":"fivetran_wick_crumpet_staging","name":"lucian_public_tasks-staging-4f8f229f-5b71-465a-8c71-fe4a47e25695"}	2022-02-09 19:16:13.412 +0000	logic_exporting	b5e47b18-dc88-4246-9f33-64512205e195	16,117	4e4d37a2-b9b9-43be-b9ea-45715f302903
```

Should the `stg_fivetran_log__log` model select the most recent row based on `SEQUENCE_NUMBER`? 

**Expected behavior**
I would expect the `stg_fivetran_log__log` model ([here](https://github.com/fivetran/dbt_fivetran_log/blob/main/models/staging/stg_fivetran_log__log.sql)) to handle duplicate rows. The model could either "just" select one of the two rows at random or (see above) grab the row with the larger `SEQUENCE_NUMBER` **assuming** that a later sequence number means the row came later and presumably is the "right" row to reference. 

**Project variables configuration**
```yml
vars:
  fivetran_log:
    # Link to the package that relies on these vars:
    # https://hub.getdbt.com/fivetran/fivetran_log/latest/
    fivetran_log_database: raw
    fivetran_log_schema: fivetran_logs

models:
  fivetran_log:
    # Explicitly excluding because the runtime of this model is extremely slow,
    # it's taken as long as 14 minutes to build this one table. We don't use 
    # this model, therefore there's no reason to slow down build time for it
    fivetran_log__audit_table:
      +enabled: false

```

**Package Version**
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.0

  - package: dbt-labs/segment
    version: 0.7.0

  - package: fivetran/fivetran_log
    version: 0.5.0

  - package: fivetran/salesforce_source
    version: 0.4.1

  - package: fivetran/salesforce
    version: 0.5.1

  - package: fivetran/jira
    version: 0.7.0

  - package: calogica/dbt_date
    version: 0.5.2

  - package: brooklyn-data/dbt_artifacts
    version: 0.6.0 #updated to 0.7.0, got a failed dbt test. checking in dbt slack about the error but reverting the change in the meantime back to 0.6.0

  - package: entechlog/dbt_snow_mask
    version: 0.1.6

  - package: fivetran/github
    version: 0.4.0

  - package: fivetran/github_source
    version: 0.4.1
  
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5

```

**Warehouse**
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Screenshots**
The test failures in dbt Cloud:
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/1261230/153863102-a89f4502-ff51-4a82-9947-32ed83fd69c2.png">

Screenshot from Snowflake showing that the rows are identical _except_ the `sequence_number` column 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1261230/153863223-1d8c63a5-0c65-4374-be7e-7c3318803639.png">

**Please indicate the level of urgency** 
This is currently causing all of our production runs of dbt to "fail" because these tests don't pass. We also haven't been able to figure out how to overwrite the test severity to `warn`.
Low to moderate level of severity. 

**Are you interested in contributing to this package?** 
- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
