### ISSUE TITLE
Syntax Error with Additional Configuration

### ISSUE THREAD

**Issue by angel-hernandez91** [fivetran/dbt_fivetran_log#4]
When attempting use the additional configuration to skip creating empty `transformation` and `trigger_table tables` I receive the following error:

```
Running with dbt=0.18.0
Encountered an error:
Runtime Error
  Syntax error near line 38
  ------------------------------
  35 | models:
  36 |   fivetran_log_transformation_status:
  37 |       +enabled: false
  38 |     staging:
  39 |       stg_fivetran_log_trigger_table:
  40 |         +enabled: false
  41 |       stg_fivetran_log_transformation:

  Raw Error:
  ------------------------------
  while parsing a block mapping
    in "<unicode string>", line 36, column 3:
        fivetran_log_transformation_status:
        ^
  expected <block end>, but found '<block mapping start>'
    in "<unicode string>", line 38, column 5:
          staging:
          ^
```

This is how my `dbt_package.yml` is currently laid out:

```
name: sales_engineers

config-version: 2
version: '0.0.1'

# Need to Check With Team To Ensure That Custom Profiles Are Not Supported
profile: fivetran_dbt

require-dbt-version: [">=0.17.0", "<=0.18.0"]

# See Quoting Docs for Snowflake
# https://docs.getdbt.com/reference/project-configs/quoting
quoting:
  database: false
  schema: false
  identifier: false

vars:
  fivetran_log:
      unioning_multiple_destinations: false # disables macro for combining multiple destinations' Log Connectors"
      account: "{{ source('fivetran_log', 'account') }}" 
      account_membership: "{{ source('fivetran_log', 'account_membership') }}"
      active_volume: "{{ source('fivetran_log', 'active_volume') }}"
      connector: "{{ source('fivetran_log', 'connector') }}"  
      credits_used: "{{ source('fivetran_log', 'credits_used') }}"
      destination: "{{ source('fivetran_log', 'destination') }}"
      destination_membership: "{{ source('fivetran_log', 'destination_membership') }}" 
      log: "{{ source('fivetran_log', 'log') }}" 
      transformation: "{{ source('fivetran_log', 'transformation') }}"
      trigger_table: "{{ source('fivetran_log', 'trigger_table') }}"
      user: "{{ source('fivetran_log', 'user') }}"

models:
  fivetran_log_transformation_status:
      +enabled: false
    staging:
      stg_fivetran_log_trigger_table:
        +enabled: false
      stg_fivetran_log_transformation:
        +enabled: false

```
