### ISSUE TITLE
[Bug] stg_fivetran_log__log unique_combination_of_columns test is too strict

### ISSUE THREAD

**Issue by samkessaram** [fivetran/dbt_fivetran_log#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The dbt_utils.unique_combination_of_columns test for the stg_fivetran_log__log model is failing in my project, but when I look at some failing rows I see that they are distinct events. 

e.g. 

| LOG_ID  | CREATED_AT          | CONNECTOR_ID | EVENT_TYPE | MESSAGE_DATA                              | EVENT_SUBTYPE        | TRANSFORMATION_ID |
| ------- | ------------------- | ------------ | ---------- | ----------------------------------------- | -------------------- | ----------------- |
| some_id | 2021-03-01 05:10:15 | some_id      | INFO       | {"schema":"schema_name","name":"some_id"} | copy_rows            |                   |
| some_id | 2021-03-01 05:10:15 | some_id      | INFO       | {"table":"table_name"}                    | write_to_table_start |                   |

The test:

```
- name: stg_fivetran_log__log
    description: > 
      Table of logged events related to data syncs. More info on error logs 
      [here](https://fivetran.com/docs/logs/fivetran-log#errorlogs)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - log_id
            - created_at
```

### Relevant error log or model output

```shell
Failure in test dbt_utils_unique_combination_of_columns_stg_fivetran_log__log_log_id__created_at (models/staging/stg_fivetran_log.yml)
  Got 1 results, configured to fail if != 0
```

### Expected behavior

I assume that the intention is to flag duplicate logs, so the case that I posted above shouldn't cause a failure since the values for the additional columns are different between the rows. 

### dbt Project configurations

```
vars:
  fivetran_log:
    fivetran_log_database: [our db]
    fivetran_log_schema: fivetran_log
    fivetran_log_using_transformations: false # this will disable all transformation + trigger_table logic 
    fivetran_log_using_triggers: false # this will disable only trigger_table logic
```

### Package versions

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.4
  - package: fivetran/fivetran_log
    version: 0.4.1
```

### What database are you using dbt with?

snowflake

### dbt Version

`dbt=0.21.0`

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
