### ISSUE TITLE
[Bug] duplicate rows in fivetran_log__schema_changelog

### ISSUE THREAD

**Issue by CraigWilson-ZOE** [fivetran/dbt_fivetran_log#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Running the latest version of the fivetran_log package I am getting the following test failure:
```
dbt_utils_unique_combination_of_columns_fivetran_log__schema_changelog_connector_id__destination_id__created_at
```

### Relevant error log or model output

```shell
The result of the query shows many records showing the same schema change, or difference schema changes happening at the same time i.e. (JSON output from BigQuery):

{  "connector_id": "dashing_overbite",  "created_at": "2022-03-31T18:34:14.412Z",  "message_data": "{\"type\":\"ADD_COLUMN\",\"table\":\"people\",\"properties\":{\"columnName\":\"_2022_q_1_survey_adherence\",\"dataType\":\"STRING\"}}"}
{  "connector_id": "dashing_overbite",  "created_at": "2022-03-31T18:34:14.412Z",  "message_data": "{\"type\":\"ADD_COLUMN\",\"table\":\"people\",\"properties\":{\"columnName\":\"check_in_start\",\"dataType\":\"TIMESTAMP\"}}"}
{  "connector_id": "dashing_overbite",  "created_at": "2022-03-31T18:34:14.412Z",  "message_data": "{\"type\":\"ADD_COLUMN\",\"table\":\"people\",\"properties\":{\"columnName\":\"_2022_q_1_survey_weight_improvement\",\"dataType\":\"STRING\"}}"}
{  "connector_id": "dashing_overbite",  "created_at": "2022-03-31T18:34:14.412Z",  "message_data": "{\"type\":\"ADD_COLUMN\",\"table\":\"people\",\"properties\":{\"columnName\":\"_2022_q_1_survey_no_improvement\",\"dataType\":\"STRING\"}}"}


As you can see from above, each of the above are different columns added at exactly the same time.

In another example it shows the exact same column added twice at the same time:
```json
{  "connector_id": "doing_dispelled",  "created_at": "2022-04-08T09:42:33.300Z",  "message_data": "{\"type\":\"ADD_COLUMN\",\"table\":\"ad_history\",\"properties\":{\"columnName\":\"placement_specific_instagram_advertising_policies\",\"dataType\":\"STRING\"}}"}
{  "connector_id": "doing_dispelled",  "created_at": "2022-04-08T09:42:33.300Z",  "message_data": "{\"type\":\"ADD_COLUMN\",\"table\":\"ad_history\",\"properties\":{\"columnName\":\"placement_specific_facebook_advertising_policies\",\"dataType\":\"STRING\"}}"}
```
```


### Expected behavior

Test doesn't fail

### dbt Project configurations

Only including specifics for Fivetran configuration:
```yaml
name: dbt_elt
version: '1.0.0'
config-version: 2

vars:
    # Fivetran log package configuration
    fivetran_log:
      fivetran_log_database: my_gcp_project
      fivetran_log_schema: fivetran_log
      fivetran_log_using_transformations: false # this will disable all transformation + trigger_table logic
      fivetran_log_using_triggers: false # this will disable only trigger_table logic
```

### Package versions

```yaml
packages:
  - package: fivetran/stripe_source
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/stripe
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/fivetran_log
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/mailchimp_source
    version: [">=0.3.0", "<0.4.0"]
  - package: fivetran/mailchimp
    version: [">=0.6.0", "<0.7.0"]
```

### What database are you using dbt with?

bigquery

### dbt Version

1.0.1

### Additional Context

N/A

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
