### ISSUE TITLE
[Duplicate Credits Spent] fivetran_log__usage_mar_destination_history dups

### ISSUE THREAD

**Issue by lord-skinner** [fivetran/dbt_fivetran_log#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The cte [here](https://github.com/fivetran/dbt_fivetran_log/blob/9f89183075bf03938f81044b673cfb231e353443/models/fivetran_log__usage_mar_destination_history.sql#L30) is generating duplicate credits spent rows:

![image](https://user-images.githubusercontent.com/105675751/200667354-a1e8038b-66bf-4990-acdb-260487465b89.png)

### Relevant error log or model output

```shell
Failure in test dbt_utils_unique_combination_of_columns_fivetran_log__usage_mar_destination_history_destination_id__measured_month (models\fivetran_log.yml)
```

### Expected behavior

unique combination of columns test passes

### dbt Project configurations

```
vars:
    ## fivetran log package configuration vars
    fivetran_log_database: elastic-bi
    fivetran_log_schema: fivetran_log
    fivetran_log_using_transformations: false
    fivetran_log_using_triggers: false
```

### Package versions

```
packages:
  - package: dbt-labs/codegen
    version: [">=0.8.0", "<0.9.0"]
    ## Docs: https://hub.getdbt.com/dbt-labs/codegen/latest/
  - package: dbt-labs/dbt_external_tables
    version: [">=0.8.0", "<0.9.0"]
    ## Docs: https://hub.getdbt.com/dbt-labs/dbt_external_tables/latest/
  - package: elementary-data/elementary
    version: [">=0.5.0", "<0.6.0"]
    ## Docs: https://hub.getdbt.com/elementary-data/elementary/latest/
  - package: fivetran/fivetran_log
    version: [">=0.6.0", "<0.7.0"]
    ## Docs: https://hub.getdbt.com/fivetran/fivetran_log/latest/
  - package: fivetran/netsuite
    version: [">=0.6.0", "<0.7.0"]
    ## Docs: https://hub.getdbt.com/fivetran/netsuite/latest/
  - package: fivetran/salesforce_formula_utils
    version: [">=0.7.0", "<0.8.0"]
    ## Docs: https://hub.getdbt.com/fivetran/salesforce_formula_utils/latest/
```

### What database are you using dbt with?

bigquery

### dbt Version

`dbt-bigquery==1.3.*`

### Additional Context

My initial thoughts are that this is being caused by [this coalesce statement](https://github.com/fivetran/dbt_fivetran_log/blob/9f89183075bf03938f81044b673cfb231e353443/models/fivetran_log__usage_mar_destination_history.sql#L363), but I haven't had time to dig in.

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
