### ISSUE TITLE
[Bug] Runtime Error in `does_table_exist` macro

### ISSUE THREAD

**Issue by dimoschi** [fivetran/dbt_fivetran_log#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

While building, compiling or generating logs in a project that uses `dbt_fivetran_log` package with a Snowflake target, a weird error pops up randomly. The error is about approximate match by `adapter.get_relation` which is used in `does_table_exist` macro/

### Relevant error log or model output

```shell
23:14:22  Encountered an error:
Runtime Error
  Compilation Error in model stg_fivetran_log__usage_cost (models/staging/stg_fivetran_log__usage_cost.sql)
    When searching for a relation, dbt found an approximate match. Instead of guessing 
    which relation to use, dbt will move on. Please delete "FINANCIAL_DB"."SHOPIFY"."ORDER", or rename it to be less ambiguous.
    Searched for: FINANCIAL_DB.SHOPIFY."ORDER"
    Found: "FINANCIAL_DB"."SHOPIFY"."ORDER"
    
    > in macro does_table_exist (macros/does_table_exist.sql)
    > called by model stg_fivetran_log__usage_cost (models/staging/stg_fivetran_log__usage_cost.sql)
```

### Expected behavior

As the searched table is totally unrelated with the usage of `does_table_exist` my expectation is that no error should exist.

### dbt Project configurations

Specifically for the package we use the following
```yaml
  fivetran_log:
    +tags: [monitoring, fivetran_log]
    +database: "{{ env_var('CURATED_DB', 'DEV_CURATED_DB') }}"
    +schema: MONITORING
    staging:
      +tags: staging
      +materialized: view
      +database: "{{ env_var('STAGING_DB', 'DEV_STAGING_DB') }}"
      +schema: MONITORING # leave blank for just the target_schema
```

### Package versions

```yaml
packages:
  - package: fivetran/xero
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/hubspot
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/shopify
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/fivetran_log
    version: [">=0.7.0", "<0.8.0"]
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/codegen
    version: [">=0.9.0", "<1.0.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

❯ dbt --version
Core:
  - installed: 1.3.2
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
