### ISSUE TITLE
[Bug] Version 1.1.0 Breaking in Postgres

### ISSUE THREAD

**Issue by bcutler2919** [fivetran/dbt_fivetran_log#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When trying to run the new package version in Postgres I'm receiving errors when running `dbt run --select fivetran_log --full-refresh` 

### Relevant error log or model output

```shell
Error in model stg_fivetran_platform__log (models/staging/stg_fivetran_platform__log.sql)
18:59:38    operator does not exist: json ~~ unknown
18:59:38    LINE 118: ...en transformation_id is not null and message_data like '%has...
18:59:38                                                                   ^
18:59:38    HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
18:59:38    compiled Code at target/run/fivetran_log/models/staging/stg_fivetran_platform__log.sql
```

### Expected behavior

I would expect all staging and production models to be created with no issue. 

### dbt Project configurations

```
Name: 'project'
version: '1.0.0'
config-version: 2
profile: 'default'

vars:
  # this will disable all transformation + trigger_table logic
  fivetran_platform_using_transformations: false
  # this will disable only trigger_table logic
  fivetran_platform_using_triggers: false
  # this will disable only the destination membership logic
  fivetran_platform_using_destination_membership: false


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
```

### Package versions

```
packages:
  - package: fivetran/fivetran_log
    version: 1.1.0
```

### What database are you using dbt with?

postgres

### dbt Version

dbt version: 1.6.5
dbt-postgres version: 1.6.5

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
